/**
 * 主进程与渲染进程之间的 IPC 通道名, 两侧都从这里引用.
 */
export const IPC_CHANNELS = {
  preferencesGetSnapshot: "preferences:get-snapshot",
  preferencesSetThemeSource: "preferences:set-theme-source",
  preferencesSetLanguage: "preferences:set-language",
  vaultGetStatus: "vault:get-status",
  vaultSetupWithMasterPassword: "vault:setup-with-master-password",
  vaultSetupWithoutMasterPassword: "vault:setup-without-master-password",
  vaultUnlock: "vault:unlock",
  recoveryVerifyWords: "recovery:verify-words",
  recoveryRestoreWithMasterPassword: "recovery:restore-with-master-password",
  recoveryRestoreWithoutMasterPassword:
    "recovery:restore-without-master-password",
  recoverySaveTextFile: "recovery:save-text-file",
  entriesList: "entries:list",
  entriesGet: "entries:get",
  entriesCreate: "entries:create",
  entriesUpdate: "entries:update",
  entriesRemove: "entries:remove",
  entriesCopyField: "entries:copy-field",
  entriesCopyCustomField: "entries:copy-custom-field",
  entriesSearch: "entries:search",
  foldersList: "folders:list",
  foldersCreate: "folders:create",
  foldersRename: "folders:rename",
  foldersRemove: "folders:remove",
  foldersAssignEntry: "folders:assign-entry",
  tagsList: "tags:list",
  tagsCreate: "tags:create",
  tagsUpdate: "tags:update",
  tagsRemove: "tags:remove",
  batchRemoveEntries: "batch:remove-entries",
  batchMoveEntries: "batch:move-entries",
  batchAddTag: "batch:add-tag",
  batchRemoveTag: "batch:remove-tag",
  totpGetCode: "totp:get-code",
  totpRevealSecret: "totp:reveal-secret",
  totpCopyCode: "totp:copy-code",
  totpCopySecret: "totp:copy-secret",
  totpDecodeQrImage: "totp:decode-qr-image",
  attachmentsList: "attachments:list",
  attachmentsAddFromDialog: "attachments:add-from-dialog",
  attachmentsAddPaths: "attachments:add-paths",
  attachmentsSaveAs: "attachments:save-as",
  attachmentsOpen: "attachments:open",
  attachmentsPreview: "attachments:preview",
  attachmentsRemove: "attachments:remove",
  linksOpenExternal: "links:open-external",
} as const;
